import { ChangeEvent, useEffect, useMemo, useState } from 'react'
import { api, deleteJSON, getJSON, getPaginated, postJSON, putJSON } from '../lib/api'
import type { Channel, ChannelForm, ChannelURLStat } from '../types'

type KeyRow = { key_index?: number; api_key: string; note?: string; allowed_models?: string[]; detected_models?: string[]; model_scope_empty?: boolean; cost_multiplier?: number; priority?: number; disabled?: boolean; cooldown_until?: number }
type EditorResponse = { channel?: Channel; keys?: KeyRow[]; url_stats?: { items?: ChannelURLStat[] }; management_account?: Record<string, unknown> }
const modelName = (value: string | { model?: unknown }) => typeof value === 'string' ? value : String(value.model ?? '')
const keyName = (value: string | KeyRow) => typeof value === 'string' ? value : value.api_key
const csv = (value: string) => value.split(/[\n,]/).map((item) => item.trim()).filter(Boolean)
const protocols = ['', 'anthropic', 'codex', 'openai', 'gemini']
const parseJSON = (value: string, fallback: unknown = undefined) => { try { return JSON.parse(value) } catch { return fallback } }

export function ChannelsPage() {
  const [rows, setRows] = useState<Channel[]>([]); const [count, setCount] = useState(0); const [search, setSearch] = useState(''); const [status, setStatus] = useState('all'); const [authType, setAuthType] = useState('all'); const [modelFilter, setModelFilter] = useState(''); const [exact, setExact] = useState(false); const [page, setPage] = useState(1); const [pageSize, setPageSize] = useState(50); const [selected, setSelected] = useState<number[]>([]); const [editing, setEditing] = useState<Channel | null>(null); const [form, setForm] = useState<ChannelForm>({ name: '', auth_type: 'api_key', urls: [{ url: '' }], priority: 0, enabled: true, models: [], api_keys: [] }); const [urlStats, setUrlStats] = useState<ChannelURLStat[]>([]); const [operation, setOperation] = useState<unknown>(null); const [advanced, setAdvanced] = useState(false); const [customRules, setCustomRules] = useState('{"headers":[],"body":[]}'); const [cooldownRules, setCooldownRules] = useState('{"rules":[]}'); const [management, setManagement] = useState('{"profile":""}'); const [busy, setBusy] = useState(false); const [refreshMode, setRefreshMode] = useState<'merge' | 'replace'>('merge'); const [selectedModels, setSelectedModels] = useState<string[]>([]); const [selectedKeys, setSelectedKeys] = useState<number[]>([])
  const load = async () => { setBusy(true); try { const params: Record<string, unknown> = { limit: pageSize, offset: (page - 1) * pageSize, search, status, auth_type: authType }; if (modelFilter) params[exact ? 'model' : 'model_like'] = modelFilter; const result = await getPaginated<Channel>('/admin/channels', params); setRows(result.data); setCount(result.count); setSelected((current) => current.filter((id) => result.data.some((row) => row.id === id))) } catch (cause) { setOperation({ error: cause instanceof Error ? cause.message : '渠道加载失败' }) } finally { setBusy(false) } }
  useEffect(() => { void load() }, [page, pageSize, status, authType])
  const visible = useMemo(() => rows.filter((row) => { const name = row.name.toLowerCase(); const query = search.toLowerCase().trim(); return !query || (exact ? name === query : name.includes(query)) }), [rows, search, exact]); const totalPages = Math.max(1, Math.ceil(count / pageSize)); const updateForm = <K extends keyof ChannelForm>(key: K, value: ChannelForm[K]) => setForm((current) => ({ ...current, [key]: value }))
  const openCreate = () => { setEditing(null); setForm({ name: '', auth_type: 'api_key', urls: [{ url: '' }], priority: 0, enabled: true, models: [], api_keys: [] }); setUrlStats([]); setAdvanced(false); setSelectedModels([]); setSelectedKeys([]); setCustomRules('{"headers":[],"body":[]}'); setCooldownRules('{"rules":[]}'); setManagement('{"profile":""}') }
  const openEdit = async (row: Channel) => { setBusy(true); try { const editor = await getJSON<EditorResponse>(`/admin/channels/${row.id}/editor`); const detail = editor.channel ?? row; const keys = editor.keys ?? []; setEditing(row); setUrlStats(editor.url_stats?.items ?? []); setCustomRules(JSON.stringify(detail.custom_request_rules ?? { headers: [], body: [] }, null, 2)); setCooldownRules(JSON.stringify(detail.cooldown_detection_rules ?? { rules: [] }, null, 2)); setManagement(JSON.stringify(editor.management_account ?? detail.management_account ?? { profile: '' }, null, 2)); const models = Array.isArray(detail.model_entries) ? detail.model_entries as ChannelForm['models'] : Array.isArray(detail.models) ? detail.models.map((item) => ({ model: String(item) })) : []; setForm({ name: String(detail.name ?? row.name), auth_type: String(detail.auth_type ?? 'api_key'), urls: Array.isArray(detail.urls) ? detail.urls as ChannelForm['urls'] : [{ url: '' }], priority: Number(detail.priority ?? 0), enabled: detail.enabled !== false, models, api_keys: keys, key_strategy: String(detail.key_strategy ?? 'sequential'), rpm_limit: Number(detail.rpm_limit ?? 0), max_concurrency: Number(detail.max_concurrency ?? 0), proxy_url: String(detail.proxy_url ?? ''), websockets: Boolean(detail.websockets), protocol_transform_mode: String(detail.protocol_transform_mode ?? ''), retry_other_keys_on_failure: Boolean(detail.retry_other_keys_on_failure) }); setSelectedModels([]); setSelectedKeys([]) } catch (cause) { setOperation({ error: cause instanceof Error ? cause.message : '编辑器加载失败' }) } finally { setBusy(false) } }
  const save = async () => { if (!form.name.trim() || !form.urls.some((item) => item.url.trim())) return; const models = form.models.map((item) => typeof item === 'string' ? { model: item.trim() } : item).filter((item) => item.model); const apiKeys = (form.api_keys ?? []).map((item) => typeof item === 'string' ? { api_key: item.trim() } : item).filter((item) => item.api_key); const payload = { ...form, models, api_keys: apiKeys, custom_request_rules: parseJSON(customRules), cooldown_detection_rules: parseJSON(cooldownRules), management_account: parseJSON(management) }; setBusy(true); try { if (editing) await putJSON(`/admin/channels/${editing.id}`, payload); else await postJSON('/admin/channels', payload); setEditing(null); await load() } catch (cause) { setOperation({ error: cause instanceof Error ? cause.message : '保存失败' }) } finally { setBusy(false) } }
  const remove = async (row: Channel) => { if (!window.confirm(`确定删除渠道“${row.name}”？`)) return; await deleteJSON(`/admin/channels/${row.id}`); await load() }
  const toggleKey = async (index: number, disabled: boolean) => { if (!editing) return; await postJSON(`/admin/channels/${editing.id}/${disabled ? 'key-disable' : 'key-enable'}`, { key_index: index }); setForm((current) => ({ ...current, api_keys: (current.api_keys ?? []).map((item, itemIndex) => itemIndex === index ? { ...(typeof item === 'string' ? { api_key: item } : item), disabled } : item) })) }
  const deleteKey = async (index: number) => { if (!editing || !window.confirm('确定删除这个 API Key？')) return; await deleteJSON(`/admin/channels/${editing.id}/keys/${index}`); setForm((current) => ({ ...current, api_keys: (current.api_keys ?? []).filter((_, itemIndex) => itemIndex !== index) })); setSelectedKeys([]) }
  const cooldownKey = async (index: number, durationMs: number) => { if (!editing) return; await postJSON(`/admin/channels/${editing.id}/keys/${index}/cooldown`, { duration_ms: durationMs }); const keys = await getJSON<KeyRow[]>(`/admin/channels/${editing.id}/keys`); setForm((current) => ({ ...current, api_keys: keys })) }
  const toggleURL = async (url: string, disabled: boolean) => { if (!editing) return; await postJSON(`/admin/channels/${editing.id}/${disabled ? 'url-disable' : 'url-enable'}`, { url }); setUrlStats((current) => current.map((item) => item.url === url ? { ...item, disabled } : item)) }
  const testKey = async (index: number) => { if (!editing) return; const key = form.api_keys?.[index]; const target = form.models[0]; const apiKey = key ? keyName(key as string | KeyRow) : ''; const model = target ? modelName(target) : ''; if (!apiKey || !model) return; setOperation(await postJSON(`/admin/channels/${editing.id}/test`, { model, stream: true, content: 'test', client_protocol: 'anthropic', key_index: index, api_key: apiKey })) }
  const testURL = async (url: string) => { if (!editing || !form.models[0]) return; setOperation(await postJSON(`/admin/channels/${editing.id}/test-url`, { model: modelName(form.models[0]), stream: true, content: 'test', client_protocol: 'anthropic', key_index: 0, base_url: url })) }
  const fetchBilling = async (index: number) => { const key = form.api_keys?.[index]; const account = parseJSON(management, {}) as Record<string, unknown>; if (!key || typeof key === 'string') return; setOperation(await postJSON('/admin/channels/billing/fetch', { profile: account.profile, base_url: account.base_url, api_key: key.api_key, access_token: account.access_token, user_id: account.user_id })) }
  const managementAction = async (action: 'balance' | 'checkin') => { if (!editing) return; setOperation(await postJSON(`/admin/channels/${editing.id}/management-account/${action}`, {})) }
  const oauthAction = async (action: 'usage' | 'quota' | 'codebuddy') => { if (!editing) return; const endpoint = action === 'usage' ? 'oauth-usage' : action === 'quota' ? 'codex-quota-reset' : 'codebuddy-checkin'; setOperation(await postJSON(`/admin/channels/${editing.id}/${endpoint}`, {})) }
  const batch = async (endpoint: string, body: unknown) => { if (!selected.length) return; setOperation(await postJSON(endpoint, body)); setSelected([]); await load() }
  const batchPrompt = async (kind: 'priority' | 'cost_multiplier' | 'rpm_limit' | 'max_concurrency') => { const raw = window.prompt(`输入${kind}值`); if (raw == null || !selected.length) return; const value = Number(raw); if (!Number.isFinite(value)) return; await batch('/admin/channels/batch-advanced', { channel_ids: selected, patch: { [kind]: value } }) }
  const batchDeleteModels = async () => { const names = window.prompt('输入要批量删除的模型，逗号分隔'); if (!names || !selected.length) return; await batch('/admin/channels/models/batch-delete', { operations: selected.map((channel_id) => ({ channel_id, models: csv(names) })) }) }
  const exportJSON = async () => { const response = await api.get('/admin/channels/export.json', { responseType: 'blob' }); const url = URL.createObjectURL(response.data as Blob); const link = document.createElement('a'); link.href = url; link.download = 'channels.json'; link.click(); window.setTimeout(() => URL.revokeObjectURL(url), 1000) }
  const importJSON = async (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; const body = new FormData(); body.append('file', file, file.name); setOperation(await api.post('/admin/channels/import.json', body).then((response) => response.data)); event.target.value = ''; await load() }
  const setKey = (index: number, patch: Partial<KeyRow>) => setForm((current) => ({ ...current, api_keys: (current.api_keys ?? []).map((item, itemIndex) => itemIndex === index ? { ...(typeof item === 'string' ? { api_key: item } : item), ...patch } : item) }))
  const setURL = (index: number, patch: Record<string, unknown>) => updateForm('urls', form.urls.map((item, itemIndex) => itemIndex === index ? { ...item, ...patch } : item)); const modelEntries = form.models.map((item) => typeof item === 'string' ? { model: item } : item)
  const deleteSelectedKeys = async () => {
    if (!editing || !selectedKeys.length) return
    setBusy(true)
    try {
      // API Key indexes shift after each deletion, so delete from the end.
      for (const index of [...selectedKeys].sort((a, b) => b - a)) await deleteJSON(`/admin/channels/${editing.id}/keys/${index}`)
      const keys = await getJSON<KeyRow[]>(`/admin/channels/${editing.id}/keys`)
      setForm((current) => ({ ...current, api_keys: keys }))
      setSelectedKeys([])
    } finally { setBusy(false) }
  }

  return <><header className="page-header"><div><h1>渠道管理</h1><p className="muted">配置渠道、Key、URL、模型和路由策略</p></div><button className="btn" onClick={() => void load()} disabled={busy}>刷新</button></header>
    <div className="toolbar"><input className="input" value={search} onChange={(event) => { setSearch(event.target.value); setPage(1) }} onKeyDown={(event) => { if (event.key === 'Enter') void load() }} placeholder="搜索渠道" /><select className="select" value={status} onChange={(event) => { setStatus(event.target.value); setPage(1) }}><option value="all">全部状态</option><option value="enabled">启用</option><option value="disabled">停用</option><option value="cooldown">冷却中</option></select><select className="select" value={authType} onChange={(event) => { setAuthType(event.target.value); setPage(1) }}><option value="all">全部认证</option><option value="api_key">API Key</option><option value="codex_oauth">Codex OAuth</option><option value="anthropic_oauth">Anthropic OAuth</option></select><input className="input" value={modelFilter} onChange={(event) => setModelFilter(event.target.value)} placeholder="模型筛选" /><label className="muted"><input type="checkbox" checked={exact} onChange={(event) => setExact(event.target.checked)} /> 精确</label><button className="btn" onClick={() => { setPage(1); void load() }}>查询</button><button className="btn btn-primary" onClick={openCreate}>新增渠道</button><button className="btn" onClick={() => void exportJSON()}>导出 JSON</button><label className="btn">导入 JSON<input hidden type="file" accept="application/json" onChange={(event) => void importJSON(event)} /></label></div>
    <div className="toolbar"><select className="select" value={refreshMode} onChange={(event) => setRefreshMode(event.target.value as 'merge' | 'replace')}><option value="merge">合并刷新模型</option><option value="replace">替换刷新模型</option></select><button className="btn" disabled={!selected.length} onClick={() => void batch('/admin/channels/models/refresh-batch', { channel_ids: selected, mode: refreshMode })}>刷新模型</button><button className="btn" disabled={!selected.length} onClick={() => void batchDeleteModels()}>批量删模型</button><button className="btn" disabled={!selected.length} onClick={() => void batch('/admin/channels/batch-enabled', { channel_ids: selected, enabled: true })}>批量启用</button><button className="btn" disabled={!selected.length} onClick={() => void batch('/admin/channels/batch-enabled', { channel_ids: selected, enabled: false })}>批量停用</button><button className="btn" disabled={!selected.length} onClick={() => void batch('/admin/channels/batch-clear-cooldowns', { channel_ids: selected })}>清除冷却</button><button className="btn" disabled={!selected.length} onClick={() => void batch('/admin/channels/batch-delete', { channel_ids: selected })}>批量删除</button><button className="btn" disabled={!selected.length} onClick={() => void batchPrompt('priority')}>批量优先级</button><button className="btn" disabled={!selected.length} onClick={() => void batchPrompt('cost_multiplier')}>批量倍率</button><button className="btn" disabled={!selected.length} onClick={() => void batchPrompt('rpm_limit')}>批量 RPM</button><button className="btn" disabled={!selected.length} onClick={() => void batchPrompt('max_concurrency')}>批量并发</button></div>
    {operation !== null && <pre className="result-pre">{JSON.stringify(operation, null, 2)}</pre>}
    {(editing || form.name) && <div className="card"><div className="toolbar"><input className="input" value={form.name} onChange={(event) => updateForm('name', event.target.value)} placeholder="渠道名称" /><select className="select" value={form.auth_type} onChange={(event) => updateForm('auth_type', event.target.value)}><option value="api_key">API Key</option><option value="codex_oauth">Codex OAuth</option><option value="anthropic_oauth">Anthropic OAuth</option><option value="antigravity_oauth">Antigravity OAuth</option><option value="xai_oauth">xAI OAuth</option><option value="codebuddy_oauth">CodeBuddy OAuth</option></select><input className="input compact" type="number" value={form.priority} onChange={(event) => updateForm('priority', Number(event.target.value))} placeholder="优先级" /><label><input type="checkbox" checked={form.enabled} onChange={(event) => updateForm('enabled', event.target.checked)} /> 启用</label><button className="btn btn-primary" disabled={busy} onClick={() => void save()}>保存</button><button className="btn" onClick={() => setEditing(null)}>取消</button></div><div className="toolbar"><input className="input" type="number" value={Number(form.rpm_limit ?? 0)} onChange={(event) => updateForm('rpm_limit', Number(event.target.value))} placeholder="RPM 限制" /><input className="input" type="number" value={Number(form.max_concurrency ?? 0)} onChange={(event) => updateForm('max_concurrency', Number(event.target.value))} placeholder="最大并发" /><input className="input wide" value={String(form.proxy_url ?? '')} onChange={(event) => updateForm('proxy_url', event.target.value)} placeholder="代理 URL" /><select className="select" value={String(form.key_strategy ?? 'sequential')} onChange={(event) => updateForm('key_strategy', event.target.value)}><option value="sequential">Key 顺序</option><option value="random">Key 随机</option><option value="weighted">按权重</option></select><select className="select" value={String(form.protocol_transform_mode ?? 'auto')} onChange={(event) => updateForm('protocol_transform_mode', event.target.value)}><option value="auto">协议转换：自动</option><option value="upstream">协议转换：上游</option><option value="local">协议转换：本地</option></select><label><input type="checkbox" checked={Boolean(form.websockets)} onChange={(event) => updateForm('websockets', event.target.checked)} /> WebSocket</label><label><input type="checkbox" checked={Boolean(form.retry_other_keys_on_failure)} onChange={(event) => updateForm('retry_other_keys_on_failure', event.target.checked)} /> 失败切换 Key</label></div>
      <h2>模型</h2><textarea className="input wide advanced-textarea" value={modelEntries.map(modelName).join(', ')} onChange={(event) => updateForm('models', csv(event.target.value))} placeholder="模型，逗号分隔" /><div className="toolbar">{modelEntries.map((entry) => <label className="muted" key={modelName(entry)}><input type="checkbox" checked={selectedModels.includes(modelName(entry))} onChange={(event) => setSelectedModels((current) => event.target.checked ? [...new Set([...current, modelName(entry)])] : current.filter((item) => item !== modelName(entry)))} />{modelName(entry)}</label>)}<button className="btn" disabled={!editing} onClick={() => void getJSON<{ models?: Array<string | { model?: string }> }>(`/admin/channels/${editing?.id}/models/fetch`).then((value) => updateForm('models', (value.models ?? []).map((item) => typeof item === 'string' ? item : String(item.model ?? ''))))}>获取模型</button><button className="btn" disabled={!editing || !selectedModels.length} onClick={() => void postJSON(`/admin/channels/${editing?.id}/models`, { models: selectedModels.map((model) => ({ model })) }).then(() => setSelectedModels([]))}>添加选中模型</button><button className="btn" disabled={!editing || !selectedModels.length} onClick={() => void postJSON('/admin/channels/models/batch-delete', { operations: [{ channel_id: editing?.id, models: selectedModels }] }).then(() => setSelectedModels([]))}>删除选中模型</button></div>
      <h2>API Key <span className="muted">({form.api_keys?.length ?? 0})</span></h2><div className="toolbar"><label className="muted"><input type="checkbox" checked={Boolean(form.api_keys?.length && selectedKeys.length === form.api_keys.length)} onChange={(event) => setSelectedKeys(event.target.checked ? (form.api_keys ?? []).map((_, index) => index) : [])} /> 全选 Key</label><button className="btn" disabled={!selectedKeys.length} onClick={() => void deleteSelectedKeys()}>删除选中 Key</button><button className="btn" disabled={!selectedKeys.length} onClick={() => void (async () => { for (const index of selectedKeys) await cooldownKey(index, 0); setSelectedKeys([]) })()}>清除 Key 冷却</button></div><div className="table-wrap"><table><thead><tr><th>选</th><th>Key</th><th>备注</th><th>模型范围</th><th>倍率</th><th>优先级</th><th>状态</th><th>操作</th></tr></thead><tbody>{(form.api_keys ?? []).map((entry, index) => { const row = typeof entry === 'string' ? { api_key: entry } : entry; const cooldown = Number(row.cooldown_until ?? 0) * 1000 > Date.now(); return <tr key={index}><td><input type="checkbox" checked={selectedKeys.includes(index)} onChange={(event) => setSelectedKeys((current) => event.target.checked ? [...new Set([...current, index])] : current.filter((item) => item !== index))} /></td><td><input className="input" value={row.api_key} onChange={(event) => setKey(index, { api_key: event.target.value })} /></td><td><input className="input" value={row.note ?? ''} onChange={(event) => setKey(index, { note: event.target.value })} /></td><td><input className="input" value={(row.allowed_models ?? []).join(', ')} onChange={(event) => setKey(index, { allowed_models: csv(event.target.value) })} /></td><td><input className="input compact" type="number" min="0" step="0.01" value={Number(row.cost_multiplier ?? 1)} onChange={(event) => setKey(index, { cost_multiplier: Number(event.target.value) })} /></td><td><input className="input compact" type="number" value={Number(row.priority ?? 0)} onChange={(event) => setKey(index, { priority: Number(event.target.value) })} /></td><td>{row.disabled ? '停用' : cooldown ? '冷却中' : row.model_scope_empty ? '无可用模型' : '正常'}</td><td><button className="btn" onClick={() => void toggleKey(index, !Boolean(row.disabled))}>{row.disabled ? '启用' : '停用'}</button><button className="btn" onClick={() => void cooldownKey(index, cooldown ? 0 : 3600000)}>冷却</button><button className="btn" onClick={() => void testKey(index)}>测试</button><button className="btn" onClick={() => void fetchBilling(index)}>倍率</button><button className="btn" onClick={() => void deleteKey(index)}>删除</button></td></tr>})}</tbody></table></div><button className="btn" onClick={() => updateForm('api_keys', [...(form.api_keys ?? []), { api_key: '', cost_multiplier: 1, priority: 0 }])}>添加 Key</button>
      <h2>上游 URL</h2><div className="table-wrap"><table><thead><tr><th>URL</th><th>精确</th><th>协议</th><th>状态</th><th>延迟</th><th>请求/失败</th><th>操作</th></tr></thead><tbody>{form.urls.map((entry, index) => { const url = String(entry.url ?? ''); const stat = urlStats.find((item) => item.url === url || item.url === `${url}#`); return <tr key={index}><td><input className="input wide" value={url} onChange={(event) => setURL(index, { url: event.target.value })} /></td><td><input type="checkbox" checked={Boolean(entry.exact)} onChange={(event) => setURL(index, { exact: event.target.checked })} /></td><td><select className="select" value={String(entry.protocol ?? '')} onChange={(event) => setURL(index, { protocol: event.target.value, protocols: event.target.value ? [event.target.value] : [] })}>{protocols.map((item) => <option key={item} value={item}>{item || '自动'}</option>)}</select></td><td>{stat?.disabled ? '停用' : stat?.cooled_down ? '冷却中' : stat?.latency_ms == null ? '-' : '正常'}</td><td>{stat?.latency_ms == null || Number(stat.latency_ms) < 0 ? '-' : `${Math.round(Number(stat.latency_ms))}ms`}</td><td>{stat ? `${Number(stat.requests ?? 0)}/${Number(stat.failures ?? 0)}` : '-'}</td><td><button className="btn" onClick={() => void testURL(url)} disabled={!url}>测试</button><button className="btn" onClick={() => void toggleURL(url, !Boolean(stat?.disabled))} disabled={!url}>{stat?.disabled ? '启用' : '停用'}</button><button className="btn" onClick={() => updateForm('urls', form.urls.filter((_, itemIndex) => itemIndex !== index))}>删除</button></td></tr>})}</tbody></table></div><button className="btn" onClick={() => updateForm('urls', [...form.urls, { url: '' }])}>添加 URL</button>
      <div className="toolbar"><button className="btn" onClick={() => setAdvanced(!advanced)}>高级规则与管理账户 JSON</button>{editing && <><button className="btn" onClick={() => void managementAction('balance')}>查询余额</button><button className="btn" onClick={() => void managementAction('checkin')}>签到</button><button className="btn" onClick={() => void oauthAction('usage')}>刷新 OAuth 用量</button><button className="btn" onClick={() => void oauthAction('quota')}>重置 Codex 配额</button><button className="btn" onClick={() => void oauthAction('codebuddy')}>CodeBuddy 签到</button></>}</div>{advanced && <div className="advanced-grid"><label>自定义请求规则<textarea className="input wide advanced-textarea" value={customRules} onChange={(event) => setCustomRules(event.target.value)} /></label><label>冷却检测规则<textarea className="input wide advanced-textarea" value={cooldownRules} onChange={(event) => setCooldownRules(event.target.value)} /></label><label>管理账户<textarea className="input wide advanced-textarea" value={management} onChange={(event) => setManagement(event.target.value)} /></label></div>}
    </div>}
    <div className="table-wrap"><table><thead><tr><th><input type="checkbox" checked={visible.length > 0 && visible.every((row) => selected.includes(row.id))} onChange={(event) => setSelected(event.target.checked ? visible.map((row) => row.id) : [])} /></th><th>渠道</th><th>类型</th><th>状态</th><th>优先级</th><th>模型</th><th>操作</th></tr></thead><tbody>{visible.map((row) => <tr key={row.id}><td><input type="checkbox" checked={selected.includes(row.id)} onChange={(event) => setSelected((current) => event.target.checked ? [...new Set([...current, row.id])] : current.filter((id) => id !== row.id))} /></td><td>{row.name}</td><td>{String(row.type ?? row.auth_type ?? '-')}</td><td>{row.enabled === false ? '停用' : '启用'}</td><td>{String(row.priority ?? 0)}</td><td>{Array.isArray(row.models) ? row.models.map(String).join(', ') : '-'}</td><td><button className="btn" onClick={() => void openEdit(row)}>编辑</button><button className="btn" onClick={() => void remove(row)}>删除</button></td></tr>)}</tbody></table></div>
    <div className="toolbar"><button className="btn" disabled={page <= 1} onClick={() => setPage((current) => current - 1)}>上一页</button><span className="muted">第 {page} / {totalPages} 页，共 {count} 个渠道</span><button className="btn" disabled={page >= totalPages} onClick={() => setPage((current) => current + 1)}>下一页</button><select className="select" value={pageSize} onChange={(event) => { setPageSize(Number(event.target.value)); setPage(1) }}><option value={20}>20/页</option><option value={50}>50/页</option><option value={100}>100/页</option></select></div>
  </>
}
