import { useEffect, useState } from 'react'
import { Link } from '@tanstack/react-router'
import { getJSON } from '../lib/api'
import type { DashboardSummary } from '../types'

export function DashboardPage() {
  const [range, setRange] = useState('today'); const [summary, setSummary] = useState<DashboardSummary>({}); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null)
  const load = async () => { setLoading(true); try { setSummary(await getJSON<DashboardSummary>('/dashboard/summary', { range })) } catch (cause) { setError(cause instanceof Error ? cause.message : '概览加载失败') } finally { setLoading(false) } }
  useEffect(() => { void load() }, [range])
  const protocols = summary.by_client_protocol ?? {}; const totals = Object.values(protocols).reduce((acc, item) => ({ requests: acc.requests + Number(item.total_requests ?? 0), success: acc.success + Number(item.success_requests ?? 0), error: acc.error + Number(item.error_requests ?? 0), cost: acc.cost + Number(item.effective_cost ?? item.total_cost ?? 0) }), { requests: 0, success: 0, error: 0, cost: 0 })
  return <><header className="page-header"><div><h1>概览</h1><p className="muted">请求量、成功率、成本和服务健康</p></div><div className="toolbar"><select className="select" value={range} onChange={(event) => setRange(event.target.value)}><option value="today">今天</option><option value="yesterday">昨天</option><option value="this_week">本周</option><option value="this_month">本月</option><option value="all">全部</option></select><button className="btn" onClick={() => void load()}>刷新</button></div></header>{error && <div className="card error-text">{error}</div>}<section className="grid grid-4"><div className="card"><div className="muted">总请求</div><div className="metric">{totals.requests.toLocaleString()}</div></div><div className="card"><div className="muted">成功</div><div className="metric">{totals.success.toLocaleString()}</div></div><div className="card"><div className="muted">失败</div><div className="metric">{totals.error.toLocaleString()}</div></div><div className="card"><div className="muted">成功率</div><div className="metric">{totals.requests ? `${(totals.success / totals.requests * 100).toFixed(1)}%` : '-'}</div></div></section><section className="grid grid-4" style={{ marginTop: 16 }}>{['anthropic', 'codex', 'openai', 'gemini'].map((key) => { const item = protocols[key] ?? {}; const total = Number(item.total_requests ?? 0); return <div className="card" key={key}><div className="muted">{key}</div><div className="metric">{total.toLocaleString()}</div><div className="muted">成功 {Number(item.success_requests ?? 0).toLocaleString()} · 失败 {Number(item.error_requests ?? 0).toLocaleString()}</div></div> })}</section><section className="card" style={{ marginTop: 16 }}><h2>快速入口</h2><div className="toolbar"><Link className="btn btn-primary" to="/channels">渠道管理</Link><Link className="btn" to="/monitor">渠道监控</Link><Link className="btn" to="/stats">统计分析</Link><Link className="btn" to="/logs">请求日志</Link></div>{loading && <p className="muted">加载中...</p>}</section></>
}
