import { useEffect, useState } from 'react'
import { api, getJSON, postJSON, putJSON } from '../lib/api'
import type { Channel } from '../types'

type Entry = { model: string; redirect_model?: string; disabled?: boolean; [key: string]: unknown }
export function ModelCatalogPage() {
  const [channels, setChannels] = useState<Channel[]>([]); const [channelId, setChannelId] = useState<number | ''>(''); const [entries, setEntries] = useState<Entry[]>([]); const [selected, setSelected] = useState<string[]>([]); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null)
  useEffect(() => { void getJSON<{ data?: Channel[] }>('/admin/channels', { limit: 500, offset: 0 }).then((value) => setChannels(value.data ?? [])) }, [])
  const fetchModels = async () => { if (!channelId) return; setBusy(true); try { const value = await getJSON<{ models?: Array<string | Entry> }>(`/admin/channels/${channelId}/models/fetch`); setEntries((value.models ?? []).map((entry) => typeof entry === 'string' ? { model: entry } : entry)) } catch (cause) { setError(cause instanceof Error ? cause.message : '模型获取失败') } finally { setBusy(false) } }
  const add = async () => { if (!channelId || !selected.length) return; await postJSON(`/admin/channels/${channelId}/models`, { models: selected.map((model) => ({ model })) }); await fetchModels() }
  const remove = async () => { if (!channelId || !selected.length) return; await api.delete(`/admin/channels/${channelId}/models`, { data: { models: selected } }); setSelected([]); await fetchModels() }
  const update = async (entry: Entry) => { if (!channelId) return; await putJSON(`/admin/channels/${channelId}/models`, { models: [entry] }); await fetchModels() }
  return <><header className="page-header"><div><h1>模型目录</h1><p className="muted">获取、添加、停用、重定向和删除渠道模型</p></div><button className="btn" onClick={() => void fetchModels()}>刷新</button></header><div className="card"><div className="toolbar"><select className="select" value={channelId} onChange={(event) => setChannelId(event.target.value ? Number(event.target.value) : '')}><option value="">选择渠道</option>{channels.map((channel) => <option key={channel.id} value={channel.id}>{channel.name}</option>)}</select><button className="btn" disabled={!channelId || busy} onClick={() => void fetchModels()}>获取模型</button><button className="btn btn-primary" disabled={!selected.length} onClick={() => void add()}>添加选中</button><button className="btn" disabled={!selected.length} onClick={() => void remove()}>删除选中</button></div>{error && <p className="error-text">{error}</p>}<div className="table-wrap"><table><thead><tr><th>选择</th><th>模型</th><th>重定向模型</th><th>状态</th><th>操作</th></tr></thead><tbody>{entries.map((entry) => <tr key={entry.model}><td><input type="checkbox" checked={selected.includes(entry.model)} onChange={(event) => setSelected((current) => event.target.checked ? [...current, entry.model] : current.filter((item) => item !== entry.model))} /></td><td>{entry.model}</td><td><input className="input" value={String(entry.redirect_model ?? '')} onChange={(event) => setEntries((current) => current.map((item) => item.model === entry.model ? { ...item, redirect_model: event.target.value } : item))} /></td><td><label><input type="checkbox" checked={!entry.disabled} onChange={(event) => setEntries((current) => current.map((item) => item.model === entry.model ? { ...item, disabled: !event.target.checked } : item))} /> 启用</label></td><td><button className="btn" onClick={() => void update(entry)}>保存</button></td></tr>)}</tbody></table></div></div></>
}
