import { useEffect, useMemo, useState } from 'react'
import { Activity, CheckCircle2, Clock3, Gauge, RefreshCw, RotateCw, Settings2, XCircle } from 'lucide-react'
import type { ReactNode } from 'react'
import { getJSON, postJSON, putJSON } from '../lib/api'

interface Probe { time: string; status_code: number; duration: number; message?: string }
interface Schedule { enabled?: boolean; interval_minutes?: number; start_time?: string; model?: string }
interface Item { id: number; name: string; enabled?: boolean; status?: string; running?: boolean; models?: string[]; effective_model?: string; next_check?: string | null; schedule?: Schedule; stats?: { samples?: number; successes?: number; average_latency?: number; last_error?: string; recent?: Probe[] } }
interface MonitorData { items?: Item[]; server_time?: string; timezone?: string }

const defaultInterval = 300
const formatTime = (value?: string | null) => value ? new Date(value).toLocaleString() : '尚未检测'
const formatLatency = (seconds?: number) => seconds == null || seconds <= 0 ? '-' : seconds < 1 ? `${Math.round(seconds * 1000)} ms` : `${seconds.toFixed(2)} s`
const statusText: Record<string, string> = { online: '稳定在线', degraded: '状态降级', offline: '离线', disabled: '已禁用', unknown: '待检测' }
const statusTone = (status?: string) => status === 'online' ? 'monitor-good' : status === 'offline' ? 'monitor-bad' : status === 'disabled' ? 'monitor-muted' : 'monitor-warn'

export function MonitorPage() {
  const [items, setItems] = useState<Item[]>([]); const [serverTime, setServerTime] = useState(''); const [timezone, setTimezone] = useState(''); const [busy, setBusy] = useState<number | null>(null); const [error, setError] = useState<string | null>(null); const [showSettings, setShowSettings] = useState(false); const [clock, setClock] = useState(() => Date.now())
  const load = async () => { try { const value = await getJSON<MonitorData>('/admin/channel-monitor'); setItems(value.items ?? []); setServerTime(value.server_time ?? ''); setTimezone(value.timezone ?? ''); setError(null) } catch (cause) { setError(cause instanceof Error ? cause.message : '加载监控失败') } }
  useEffect(() => { void load(); const refresh = () => { if (document.visibilityState === 'visible') void load() }; const timer = window.setInterval(refresh, 10_000); window.addEventListener('focus', refresh); document.addEventListener('visibilitychange', refresh); return () => { window.clearInterval(timer); window.removeEventListener('focus', refresh); document.removeEventListener('visibilitychange', refresh) } }, [])
  useEffect(() => { const timer = window.setInterval(() => setClock(Date.now()), 1000); return () => window.clearInterval(timer) }, [])
  const save = async (item: Item, patch: Schedule) => { setBusy(item.id); try { await putJSON(`/admin/channels/${item.id}/monitor-schedule`, { ...(item.schedule ?? {}), ...patch }); await load() } catch (cause) { setError(cause instanceof Error ? cause.message : '保存监测设置失败') } finally { setBusy(null) } }
  const run = async (item: Item) => { setBusy(item.id); try { await postJSON(`/admin/channels/${item.id}/monitor-run`); await load() } catch (cause) { setError(cause instanceof Error ? cause.message : '检测失败') } finally { setBusy(null) } }
  const summary = useMemo(() => { const enabled = items.filter((item) => item.enabled !== false); const online = enabled.filter((item) => item.status === 'online').length; const degraded = enabled.filter((item) => item.status === 'degraded').length; const offline = enabled.filter((item) => item.status === 'offline').length; const samples = enabled.reduce((sum, item) => sum + Number(item.stats?.samples ?? 0), 0); const successes = enabled.reduce((sum, item) => sum + Number(item.stats?.successes ?? 0), 0); const latency = enabled.map((item) => Number(item.stats?.average_latency ?? 0)).filter(Boolean); return { total: items.length, online, degraded, offline, running: items.filter((item) => item.running).length, samples, rate: samples ? successes / samples * 100 : 0, latency: latency.length ? latency.reduce((a, b) => a + b, 0) / latency.length : 0 } }, [items])
  return <>
    <header className="page-header"><div><h1>渠道监控</h1><p className="muted">实时查看每个渠道的稳定状态、响应延迟和自动检测计划</p></div><div className="toolbar"><span className="muted">{serverTime ? `服务端 ${formatTime(serverTime)} · ${timezone}` : ''}</span><button className="btn" onClick={() => void load()}><RefreshCw size={15} /> 刷新</button><button className="btn" onClick={() => setShowSettings((value) => !value)}><Settings2 size={15} /> 设置</button></div></header>
    {error && <div className="card error-text">{error}</div>}
    <section className="monitor-summary-grid"><SummaryCard icon={<Activity size={18} />} label="监测渠道" value={String(summary.total)} detail={`${summary.online} 稳定 · ${summary.degraded} 降级 · ${summary.offline} 离线`} /><SummaryCard icon={<CheckCircle2 size={18} />} label="24 小时成功率" value={summary.samples ? `${summary.rate.toFixed(1)}%` : '-'} detail={`${summary.samples} 次有效探测`} tone={summary.rate >= 95 ? 'good' : summary.rate >= 80 ? 'warn' : 'bad'} /><SummaryCard icon={<Gauge size={18} />} label="平均响应延迟" value={formatLatency(summary.latency)} detail="最近 24 小时成功探测" /><SummaryCard icon={<RotateCw size={18} />} label="自动检测" value={String(summary.running)} detail={`${summary.running} 个检测中`} tone={summary.running ? 'warn' : 'good'} /></section>
    {showSettings && <div className="card monitor-help"><strong>自动检测说明</strong><span className="muted">每个渠道单独设置间隔，服务端调度器会按保存的间隔和每日开始时间自动执行。默认间隔为 {defaultInterval} 分钟。</span></div>}
    <section className="monitor-grid">{items.map((item) => <MonitorCard key={item.id} item={item} busy={busy === item.id} clock={clock} onSave={save} onRun={run} />)}{!items.length && <div className="card monitor-empty">暂无渠道，请先在渠道页面添加并启用渠道。</div>}</section>
  </>
}

function SummaryCard({ icon, label, value, detail, tone }: { icon: ReactNode; label: string; value: string; detail: string; tone?: string }) { return <div className={`card monitor-summary-card ${tone ? `monitor-${tone}` : ''}`}><div className="monitor-summary-label">{icon}<span>{label}</span></div><div className="monitor-summary-value">{value}</div><div className="muted">{detail}</div></div> }

function MonitorCard({ item, busy, clock, onSave, onRun }: { item: Item; busy: boolean; clock: number; onSave: (item: Item, patch: Schedule) => Promise<void>; onRun: (item: Item) => Promise<void> }) {
  const [enabled, setEnabled] = useState(Boolean(item.schedule?.enabled)); const [interval, setInterval] = useState(Number(item.schedule?.interval_minutes ?? defaultInterval)); const [start, setStart] = useState(item.schedule?.start_time ?? '00:00'); const [model, setModel] = useState(item.schedule?.model ?? '')
  useEffect(() => { setEnabled(Boolean(item.schedule?.enabled)); setInterval(Number(item.schedule?.interval_minutes ?? defaultInterval)); setStart(item.schedule?.start_time ?? '00:00'); setModel(item.schedule?.model ?? '') }, [item.schedule?.enabled, item.schedule?.interval_minutes, item.schedule?.start_time, item.schedule?.model])
  const samples = Number(item.stats?.samples ?? 0); const successes = Number(item.stats?.successes ?? 0); const rate = samples ? successes / samples * 100 : 0; const recent = (item.stats?.recent ?? []).slice(0, 12).reverse(); const latest = item.stats?.recent?.[0]; const tone = statusTone(item.status); const nextMs = item.next_check ? new Date(item.next_check).getTime() - clock : 0; const savePatch = () => void onSave(item, { enabled, interval_minutes: Math.max(1, Math.min(1440, interval || defaultInterval)), start_time: start || '00:00', model: model.trim() })
  return <article className="monitor-card card"><div className="monitor-card-head"><div><div className="monitor-title"><span className={`monitor-status-dot ${tone}`} />{item.name}</div><div className="muted">#{item.id} · {item.effective_model || model || '未选择模型'}</div></div><span className={`monitor-status ${tone}`}>{item.running ? '检测中' : statusText[item.status ?? 'unknown']}</span></div><div className="monitor-metrics"><div><span className="muted">平均延迟</span><strong>{formatLatency(item.stats?.average_latency)}</strong></div><div><span className="muted">24 小时成功率</span><strong>{samples ? `${rate.toFixed(1)}%` : '-'}</strong></div><div><span className="muted">探测次数</span><strong>{samples}</strong></div></div><div className="monitor-sparkline" aria-label="最近探测稳定状态">{recent.length ? recent.map((probe, index) => <i key={`${probe.time}-${index}`} className={probe.status_code >= 200 && probe.status_code < 300 ? 'probe-good' : 'probe-bad'} title={`${formatTime(probe.time)} · ${probe.status_code || '失败'} · ${formatLatency(probe.duration)}`} />) : <span className="muted">暂无最近探测记录</span>}</div><div className="monitor-last"><span><Clock3 size={14} /> 最近：{latest ? `${formatTime(latest.time)} · ${formatLatency(latest.duration)}` : '尚未检测'}</span>{item.next_check && <span className="muted">下次：{nextMs > 0 ? `${formatCountdown(nextMs)}后` : '即将检测'} · {formatTime(item.next_check)}</span>}</div><div className="monitor-config"><label className="monitor-toggle"><input type="checkbox" checked={enabled} disabled={busy || item.enabled === false} onChange={(event) => { setEnabled(event.target.checked); void onSave(item, { enabled: event.target.checked, interval_minutes: interval, start_time: start, model }) }} /> 自动监测</label><label>间隔（分钟）<input className="input compact" type="number" min="1" max="1440" value={interval} disabled={busy} onChange={(event) => setInterval(Number(event.target.value))} /></label><label>开始时间<input className="input compact" type="time" value={start} disabled={busy} onChange={(event) => setStart(event.target.value)} /></label><label>监测模型<select className="input compact" value={model} disabled={busy} onChange={(event) => setModel(event.target.value)}><option value="">自动选择</option>{(item.models ?? []).map((name) => <option key={name} value={name}>{name}</option>)}</select></label></div><div className="monitor-actions"><button className="btn btn-primary" disabled={busy} onClick={savePatch}>保存设置</button><button className="btn" disabled={busy || item.running || item.enabled === false} onClick={() => void onRun(item)}>{item.running ? '检测中…' : '立即检测'}</button>{(item.status === 'offline' || item.status === 'degraded') && <span className="monitor-error"><XCircle size={14} /> {item.stats?.last_error || latest?.message || (item.status === 'degraded' ? '最近 24 小时存在失败探测' : '最近探测失败')}</span>}</div></article>
}

function formatCountdown(ms: number) { const seconds = Math.max(0, Math.floor(ms / 1000)); const minutes = Math.floor(seconds / 60); const hours = Math.floor(minutes / 60); if (hours) return `${hours}小时${minutes % 60}分`; if (minutes) return `${minutes}分${seconds % 60}秒`; return `${seconds}秒` }
