import { useState } from 'react'
import { postJSON } from '../lib/api'

const providers = ['codex', 'anthropic', 'antigravity', 'xai', 'zai', 'codebuddy', 'codebuddy-international', 'cursor', 'zed']
export function OAuthPage() {
  const [provider, setProvider] = useState('codex'); const [credential, setCredential] = useState(''); const [callback, setCallback] = useState(''); const [state, setState] = useState<Record<string, unknown> | null>(null); const [busy, setBusy] = useState(false); const [xaiMethod, setXaiMethod] = useState('refresh_token')
  const importCredential = async () => { setBusy(true); try { let result: unknown; if (provider === 'zai') result = await postJSON(`/admin/zai/credentials/import`, { api_key: credential }); else if (provider === 'cursor') result = await postJSON('/admin/cursor/credentials/import', { api_key: credential }); else if (provider === 'xai') result = await postJSON('/admin/xai/credentials/import/stream', { method: xaiMethod, values: credential, priority_increment: 10 }); else if (provider === 'anthropic') { const values = credential.split(/\r?\n/).map((item) => item.trim()).filter(Boolean); const results = []; for (const session_key of values) results.push(await postJSON('/admin/anthropic/oauth/cookie', { session_key })); result = results } else result = await postJSON(`/admin/${provider}/credentials/import`, JSON.parse(credential)); setState(result as Record<string, unknown>) } finally { setBusy(false) } }
  const start = async () => { setBusy(true); try { const result = await postJSON<Record<string, unknown>>(`/admin/${provider}/oauth/start`, {}); setState(result); if (result.url) window.open(String(result.url), '_blank', 'noopener,noreferrer') } finally { setBusy(false) } }
  const callbackRequest = async () => { if (!callback.trim()) return; setState(await postJSON(`/admin/${provider}/oauth/callback`, provider === 'anthropic' ? { state: state?.state ?? '', code: callback } : { callback_url: callback })) }
  const cancel = async () => { if (state?.state) setState(await postJSON(`/admin/${provider}/oauth/cancel`, { state: state.state })) }
  return <><header className="page-header"><div><h1>OAuth 凭证</h1><p className="muted">启动 OAuth、导入凭证并查看回调状态</p></div></header><div className="card"><div className="toolbar"><select className="select" value={provider} onChange={(event) => setProvider(event.target.value)}>{providers.map((value) => <option key={value} value={value}>{value}</option>)}</select><button className="btn btn-primary" disabled={busy} onClick={() => void start()}>开始 OAuth</button><button className="btn" disabled={busy || !state?.state} onClick={() => void cancel()}>取消</button></div><textarea className="input wide advanced-textarea" value={callback} onChange={(event) => setCallback(event.target.value)} placeholder={provider === 'anthropic' ? '授权码' : '回调 URL'} /><button className="btn" disabled={!callback.trim()} onClick={() => void callbackRequest()}>提交回调</button>{provider === 'xai' && <select className="select" value={xaiMethod} onChange={(event) => setXaiMethod(event.target.value)}><option value="refresh_token">Refresh Token</option><option value="sso">SSO</option></select>}<textarea className="input wide advanced-textarea" value={credential} onChange={(event) => setCredential(event.target.value)} placeholder={provider === 'zai' || provider === 'cursor' ? 'API Key' : provider === 'anthropic' ? 'session key，可多行' : '凭证 JSON'} /><button className="btn" disabled={busy || !credential.trim()} onClick={() => void importCredential()}>导入凭证</button>{state && <pre className="result-pre">{JSON.stringify(state, null, 2)}</pre>}</div></>
}
