import { useEffect, useMemo, useState } from 'react'
import { deleteJSON, getJSON, getPaginated, postJSON, putJSON } from '../lib/api'

interface TokenRow { id: number; token?: string; name?: string; description?: string; enabled?: boolean; is_active?: boolean; expires_at?: string; [key: string]: unknown }
const ids = (value: string) => value.split(',').map((item) => Number(item.trim())).filter((item) => Number.isInteger(item) && item > 0)
const models = (value: string) => value.split(',').map((item) => item.trim()).filter(Boolean)

export function TokensPage() {
  const [rows, setRows] = useState<TokenRow[]>([])
  const [filter, setFilter] = useState('')
  const [range, setRange] = useState('today')
  const [description, setDescription] = useState('')
  const [expiry, setExpiry] = useState('')
  const [daily, setDaily] = useState('0'); const [monthly, setMonthly] = useState('0'); const [totalLimit, setTotalLimit] = useState('0'); const [concurrency, setConcurrency] = useState('0')
  const [allowedModels, setAllowedModels] = useState(''); const [allowedChannels, setAllowedChannels] = useState(''); const [restriction, setRestriction] = useState('allow'); const [createActive, setCreateActive] = useState(true)
  const [created, setCreated] = useState(''); const [editing, setEditing] = useState<TokenRow | null>(null); const [allChannels, setAllChannels] = useState<Array<{ id: number; name: string }>>([]); const [availableModels, setAvailableModels] = useState<string[]>([])
  const [edit, setEdit] = useState({ description: '', expiry: '', daily: '0', monthly: '0', total: '0', concurrency: '0', models: '', channels: '', restriction: 'allow', active: true })
  const load = async () => { const result = await getJSON<{ tokens?: TokenRow[] }>('/admin/auth-tokens', { range }); setRows(result.tokens ?? []) }
  useEffect(() => { void load(); void getPaginated<{ id: number; name: string }>('/admin/channels', { limit: 500, offset: 0 }).then((result) => { setAllChannels(result.data); setAvailableModels([...new Set(result.data.flatMap((row) => Array.isArray((row as Record<string, unknown>).models) ? ((row as Record<string, unknown>).models as unknown[]).map(String) : []))].sort()) }).catch(() => undefined) }, [range])
  const visible = useMemo(() => rows.filter((row) => !filter || `${row.description ?? row.name ?? ''} ${row.token ?? ''}`.toLowerCase().includes(filter.toLowerCase())), [rows, filter])
  const create = async () => { if (!description.trim()) return; const result = await postJSON<TokenRow & { token?: string }>('/admin/auth-tokens', { description, expires_at: expiry ? new Date(expiry).getTime() : null, is_active: createActive, cost_daily_limit_usd: Number(daily) || 0, cost_monthly_limit_usd: Number(monthly) || 0, cost_limit_usd: Number(totalLimit) || 0, max_concurrency: Number(concurrency) || 0, allowed_models: models(allowedModels), allowed_channel_ids: ids(allowedChannels), channel_restriction_mode: restriction }); setCreated(String(result.token ?? '')); setDescription(''); await load() }
  const remove = async (row: TokenRow) => { if (window.confirm(`确定删除令牌“${row.description ?? row.name ?? row.id}”？`)) { await deleteJSON(`/admin/auth-tokens/${row.id}`); await load() } }
  const openEdit = (row: TokenRow) => { setEditing(row); setEdit({ description: String(row.description ?? row.name ?? ''), expiry: row.expires_at ? toDateTimeLocal(row.expires_at) : '', daily: String(row.cost_daily_limit_usd ?? 0), monthly: String(row.cost_monthly_limit_usd ?? 0), total: String(row.cost_limit_usd ?? 0), concurrency: String(row.max_concurrency ?? 0), models: Array.isArray(row.allowed_models) ? row.allowed_models.join(', ') : '', channels: Array.isArray(row.allowed_channel_ids) ? row.allowed_channel_ids.join(', ') : '', restriction: String(row.channel_restriction_mode ?? 'allow'), active: row.is_active !== false }) }
  const toDateTimeLocal = (value: unknown) => { const date = new Date(typeof value === 'number' ? value : String(value)); if (Number.isNaN(date.getTime())) return ''; const pad = (part: number) => String(part).padStart(2, '0'); return `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}T${pad(date.getHours())}:${pad(date.getMinutes())}` }
  const setExpiryPreset = (setter: (value: string) => void, days: number | null) => setter(days === null ? '' : toDateTimeLocal(Date.now() + days * 86400000))
  const saveEdit = async () => { if (!editing) return; await putJSON(`/admin/auth-tokens/${editing.id}`, { description: edit.description, is_active: edit.active, expires_at: edit.expiry ? new Date(edit.expiry).getTime() : null, cost_daily_limit_usd: Number(edit.daily) || 0, cost_monthly_limit_usd: Number(edit.monthly) || 0, cost_limit_usd: Number(edit.total) || 0, max_concurrency: Number(edit.concurrency) || 0, allowed_models: models(edit.models), allowed_channel_ids: ids(edit.channels), channel_restriction_mode: edit.restriction }); setEditing(null); await load() }
  const toggleEditChannel = (id: number) => { const current = ids(edit.channels); const next = current.includes(id) ? current.filter((item) => item !== id) : [...current, id]; setEdit({ ...edit, channels: next.join(', ') }) }
  const toggleEditModel = (model: string) => { const current = models(edit.models); const next = current.includes(model) ? current.filter((item) => item !== model) : [...current, model]; setEdit({ ...edit, models: next.join(', ') }) }
  return <><header className="page-header"><div><h1>API 访问令牌</h1><p className="muted">管理令牌、限制、模型范围和使用统计</p></div><button className="btn" onClick={() => void load()}>刷新</button></header>
    <div className="toolbar"><select className="select" value={range} onChange={(event) => { setRange(event.target.value); void load() }}><option value="today">今天</option><option value="yesterday">昨天</option><option value="this_week">本周</option><option value="this_month">本月</option><option value="all">全部</option></select><input className="input" value={filter} onChange={(event) => setFilter(event.target.value)} placeholder="搜索描述或 Token" /></div>
    <div className="card"><h2>创建令牌</h2><div className="toolbar"><input className="input" value={description} onChange={(event) => setDescription(event.target.value)} placeholder="令牌描述" /><input className="input" type="datetime-local" value={expiry} onChange={(event) => setExpiry(event.target.value)} /><button className="btn" onClick={() => setExpiryPreset(setExpiry, null)}>永不过期</button><button className="btn" onClick={() => setExpiryPreset(setExpiry, 30)}>30 天</button><button className="btn" onClick={() => setExpiryPreset(setExpiry, 90)}>90 天</button><input className="input" type="number" min="0" value={daily} onChange={(event) => setDaily(event.target.value)} placeholder="日限额 USD" /><input className="input" type="number" min="0" value={monthly} onChange={(event) => setMonthly(event.target.value)} placeholder="月限额 USD" /><input className="input" type="number" min="0" value={totalLimit} onChange={(event) => setTotalLimit(event.target.value)} placeholder="总限额 USD" /><input className="input" type="number" min="0" value={concurrency} onChange={(event) => setConcurrency(event.target.value)} placeholder="最大并发" /></div><div className="toolbar"><input className="input" list="token-model-options" value={allowedModels} onChange={(event) => setAllowedModels(event.target.value)} placeholder="允许模型，逗号分隔" /><datalist id="token-model-options">{availableModels.map((item) => <option key={item} value={item} />)}</datalist><input className="input" value={allowedChannels} onChange={(event) => setAllowedChannels(event.target.value)} placeholder="允许渠道 ID，逗号分隔" /><span className="muted">{allChannels.length} 个渠道可选</span><select className="select" value={restriction} onChange={(event) => setRestriction(event.target.value)}><option value="allow">允许列表</option><option value="deny">拒绝列表</option></select><label className="muted"><input type="checkbox" checked={createActive} onChange={(event) => setCreateActive(event.target.checked)} /> 启用</label><button className="btn btn-primary" onClick={() => void create()} disabled={!description.trim()}>创建令牌</button></div>{created && <div className="result-pre"><strong>新令牌只显示一次：</strong>{created}<button className="btn" onClick={() => void navigator.clipboard?.writeText(created)}>复制</button></div>}</div>
    {editing && <div className="card"><div className="toolbar"><h2>编辑令牌</h2><button className="btn" onClick={() => setEditing(null)}>取消</button><button className="btn btn-primary" onClick={() => void saveEdit()}>保存</button></div><p className="muted">令牌 ID：{editing.id}</p><div className="toolbar"><input className="input" value={edit.description} onChange={(event) => setEdit({ ...edit, description: event.target.value })} placeholder="描述" /><input className="input" type="datetime-local" value={edit.expiry} onChange={(event) => setEdit({ ...edit, expiry: event.target.value })} /><button className="btn" onClick={() => setEdit({ ...edit, expiry: '' })}>永不过期</button><button className="btn" onClick={() => setEdit({ ...edit, expiry: toDateTimeLocal(Date.now() + 30 * 86400000) })}>30 天</button><button className="btn" onClick={() => setEdit({ ...edit, expiry: toDateTimeLocal(Date.now() + 90 * 86400000) })}>90 天</button><input className="input" type="number" value={edit.daily} onChange={(event) => setEdit({ ...edit, daily: event.target.value })} placeholder="日限额" /><input className="input" type="number" value={edit.monthly} onChange={(event) => setEdit({ ...edit, monthly: event.target.value })} placeholder="月限额" /><input className="input" type="number" value={edit.total} onChange={(event) => setEdit({ ...edit, total: event.target.value })} placeholder="总限额" /><input className="input" type="number" value={edit.concurrency} onChange={(event) => setEdit({ ...edit, concurrency: event.target.value })} placeholder="并发" /></div><div className="toolbar"><input className="input" value={edit.models} onChange={(event) => setEdit({ ...edit, models: event.target.value })} placeholder="允许模型" /><input className="input" value={edit.channels} onChange={(event) => setEdit({ ...edit, channels: event.target.value })} placeholder="允许渠道 ID" /><select className="select" value={edit.restriction} onChange={(event) => setEdit({ ...edit, restriction: event.target.value })}><option value="allow">允许列表</option><option value="deny">拒绝列表</option></select><label><input type="checkbox" checked={edit.active} onChange={(event) => setEdit({ ...edit, active: event.target.checked })} /> 启用</label></div><div className="toolbar"><span className="muted">渠道快速选择</span>{allChannels.map((channel) => <label className="muted" key={channel.id}><input type="checkbox" checked={ids(edit.channels).includes(channel.id)} onChange={() => toggleEditChannel(channel.id)} />{channel.name}</label>)}</div><div className="toolbar"><span className="muted">模型快速选择</span>{availableModels.map((model) => <label className="muted" key={model}><input type="checkbox" checked={models(edit.models).includes(model)} onChange={() => toggleEditModel(model)} />{model}</label>)}</div></div>}
    <div className="table-wrap"><table><thead><tr><th>令牌</th><th>状态</th><th>过期</th><th>调用</th><th>成功率</th><th>RPM</th><th>Token 用量</th><th>成本</th><th>流式首字节</th><th>非流式耗时</th><th>模型限制</th><th>渠道限制</th><th>操作</th></tr></thead><tbody>{visible.map((row) => { const success = Number(row.success_count ?? 0); const failure = Number(row.failure_count ?? 0); const total = success + failure; return <tr key={row.id}><td>{row.description ?? row.name ?? row.id}</td><td>{row.is_active === false || row.enabled === false ? '停用' : '启用'}</td><td>{row.expires_at ? new Date(Number(row.expires_at)).toLocaleString() : '永不过期'}</td><td>{total}</td><td>{total ? `${(success / total * 100).toFixed(1)}%` : '-'}</td><td>{Number(row.peak_rpm ?? row.avg_rpm ?? 0).toFixed(1)}</td><td>{(Number(row.prompt_tokens_total ?? 0) + Number(row.completion_tokens_total ?? 0)).toLocaleString()}</td><td>{Number(row.effective_cost_usd ?? row.total_cost_usd ?? 0).toFixed(4)}</td><td>{Number(row.stream_avg_ttfb ?? 0).toFixed(2)}s</td><td>{Number(row.non_stream_avg_rt ?? 0).toFixed(2)}s</td><td>{Array.isArray(row.allowed_models) && row.allowed_models.length ? row.allowed_models.join(', ') : '无限制'}</td><td>{Array.isArray(row.allowed_channel_ids) && row.allowed_channel_ids.length ? `${row.channel_restriction_mode === 'deny' ? '排除' : '允许'} ${row.allowed_channel_ids.join(', ')}` : '无限制'}</td><td><button className="btn" onClick={() => void navigator.clipboard?.writeText(String(row.token ?? ''))}>复制 Hash</button><button className="btn" onClick={() => openEdit(row)}>编辑</button><button className="btn" onClick={() => void remove(row)}>删除</button></td></tr> })}</tbody></table></div>
  </>
}
