import { useEffect, useMemo, useState } from 'react'
import { getJSON } from '../lib/api'

type Point = Record<string, unknown>
type ChannelMetric = Record<string, unknown>
const metricValue = (point: Point, metric: string) => metric === 'count' ? Number(point.success ?? 0) + Number(point.error ?? 0) : metric === 'total_tokens' ? Number(point.input_tokens ?? 0) + Number(point.output_tokens ?? 0) : Number(point[metric] ?? 0)
const channelMetricValue = (point: Point, name: string, metric: string) => { const channels = point.channels; const value = channels && typeof channels === 'object' ? (channels as Record<string, ChannelMetric>)[name] : undefined; return value ? metricValue(value, metric) : 0 }

export function TrendPage() {
  const [range, setRange] = useState('today'); const [bucket, setBucket] = useState('5'); const [channel, setChannel] = useState(''); const [model, setModel] = useState(''); const [protocol, setProtocol] = useState(''); const [token, setToken] = useState(''); const [start, setStart] = useState(''); const [end, setEnd] = useState(''); const [metric, setMetric] = useState('count'); const [chart, setChart] = useState<'line' | 'bar'>('line'); const [points, setPoints] = useState<Point[]>([]); const [selectedSeries, setSelectedSeries] = useState<string[]>([]); const [options, setOptions] = useState<{ models?: string[]; channels?: Array<{ id?: number; name?: string }> }>({}); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null)
  const query = () => ({ range, bucket_min: Number(bucket), channel_name_like: channel || undefined, model: model || undefined, client_protocol: protocol || undefined, auth_token_id: token || undefined, start_time: range === 'custom' ? start : undefined, end_time: range === 'custom' ? end : undefined })
  const load = async () => { setLoading(true); setError(null); try { setPoints(await getJSON<Point[]>('/dashboard/metrics', query())) } catch (cause) { setError(cause instanceof Error ? cause.message : '趋势加载失败') } finally { setLoading(false) } }
  const loadOptions = async () => { try { setOptions(await getJSON<typeof options>('/dashboard/models', { range })) } catch { setOptions({}) } }
  useEffect(() => { void load(); void loadOptions() }, [range, bucket])
  const channels = useMemo(() => { const names = new Set<string>(); points.forEach((point) => { const groups = point.channels; if (groups && typeof groups === 'object') Object.keys(groups as object).forEach((name) => names.add(name)) }); return [...names].sort() }, [points])
  const series = selectedSeries.length ? selectedSeries : ['总计']; const values = useMemo(() => points.map((point) => series.reduce((sum, name) => sum + (name === '总计' ? metricValue(point, metric) : channelMetricValue(point, name, metric)), 0)), [points, metric, series]); const max = Math.max(1, ...values.map((value) => Math.abs(value)))
  const pointsForSvg = values.map((value, index) => `${values.length <= 1 ? 50 : index / (values.length - 1) * 100},${96 - Math.max(0, value) / max * 88}`).join(' ')
  return <><header className="page-header"><div><h1>请求趋势</h1><p className="muted">按时间查看多渠道请求、延迟、Token 和成本</p></div><button className="btn" onClick={() => void load()} disabled={loading}>刷新</button></header><div className="toolbar"><select className="select" value={range} onChange={(event) => setRange(event.target.value)}><option value="today">今天</option><option value="yesterday">昨天</option><option value="this_week">本周</option><option value="this_month">本月</option><option value="custom">自定义</option></select><select className="select" value={bucket} onChange={(event) => setBucket(event.target.value)}><option value="1">1 分钟</option><option value="5">5 分钟</option><option value="15">15 分钟</option><option value="60">1 小时</option></select><input className="input" list="trend-channels" value={channel} onChange={(event) => setChannel(event.target.value)} placeholder="渠道" /><datalist id="trend-channels">{(options.channels ?? []).map((item) => <option key={item.id ?? item.name} value={item.name} />)}</datalist><input className="input" list="trend-models" value={model} onChange={(event) => setModel(event.target.value)} placeholder="模型" /><datalist id="trend-models">{(options.models ?? []).map((item) => <option key={item} value={item} />)}</datalist><select className="select" value={protocol} onChange={(event) => setProtocol(event.target.value)}><option value="">全部入口协议</option><option value="openai">OpenAI</option><option value="anthropic">Anthropic</option><option value="gemini">Gemini</option><option value="codex">Codex</option></select><input className="input" value={token} onChange={(event) => setToken(event.target.value)} placeholder="Token ID" />{range === 'custom' && <><input className="input" type="datetime-local" value={start} onChange={(event) => setStart(event.target.value)} /><input className="input" type="datetime-local" value={end} onChange={(event) => setEnd(event.target.value)} /></>}<select className="select" value={metric} onChange={(event) => setMetric(event.target.value)}><option value="count">调用次数</option><option value="success">成功</option><option value="error">失败</option><option value="total_tokens">Token</option><option value="effective_cost">成本</option><option value="avg_first_byte_time_seconds">首字节耗时</option><option value="avg_duration_seconds">平均耗时</option></select><select className="select" value={chart} onChange={(event) => setChart(event.target.value as 'line' | 'bar')}><option value="line">折线</option><option value="bar">柱状</option></select><button className="btn btn-primary" onClick={() => void load()}>查询</button></div>{error && <div className="card error-text">{error}</div>}
    <div className="card"><div className="toolbar"><strong>{metric}</strong><span className="muted">共 {points.length} 个时间桶</span></div>{loading ? <div>加载中...</div> : values.length === 0 ? <div>暂无数据</div> : chart === 'line' ? <svg className="trend-svg" viewBox="0 0 100 100" preserveAspectRatio="none" role="img" aria-label="趋势折线"><polyline points={pointsForSvg} fill="none" stroke="var(--accent, #60a5fa)" strokeWidth="1.5" vectorEffect="non-scaling-stroke" />{values.map((value, index) => <circle key={index} cx={values.length <= 1 ? 50 : index / (values.length - 1) * 100} cy={96 - Math.max(0, value) / max * 88} r="1.2" fill="var(--accent, #60a5fa)" />)}</svg> : <div className="trend-bars trend-bar-chart">{values.map((value, index) => <div className="trend-bar" key={index} title={`${new Date(String(points[index].ts ?? '')).toLocaleString()} · ${value}`} style={{ height: `${Math.max(4, Math.abs(value) / max * 100)}%` }} />)}</div>}</div>
    {channels.length > 0 && <div className="card"><h2>渠道序列</h2><div className="toolbar">{channels.map((name) => <label className="btn" key={name}><input type="checkbox" checked={selectedSeries.includes(name)} onChange={(event) => setSelectedSeries((current) => event.target.checked ? [...current, name] : current.filter((item) => item !== name))} /> {name}</label>)}</div></div>}
  </>
}
